"""Used public APIs of PySide6-Fluent-Widgets 1.11 (upstream ships no stubs)."""

from collections.abc import Callable
from enum import Enum
from typing import overload

from PySide6.QtCore import QPoint, Signal
from PySide6.QtGui import QIcon
from PySide6.QtWidgets import (
    QCheckBox,
    QDoubleSpinBox,
    QLabel,
    QLineEdit,
    QListWidget,
    QMenu,
    QPlainTextEdit,
    QProgressBar,
    QPushButton,
    QScrollArea,
    QSpinBox,
    QTableView,
    QTableWidget,
    QTreeWidget,
    QWidget,
)

class Theme(Enum):
    LIGHT = "Light"
    DARK = "Dark"
    AUTO = "Auto"

class FluentIcon(Enum):
    ADD = "Add"
    DELETE = "Delete"
    DOCUMENT = "Document"
    DOWNLOAD = "Download"
    EDIT = "Edit"
    FOLDER = "Folder"
    FOLDER_ADD = "FolderAdd"
    HISTORY = "History"
    LIBRARY = "BookShelf"
    MUSIC = "Music"
    MUSIC_FOLDER = "MusicFolder"
    SAVE = "Save"
    SEARCH = "Search"
    SETTING = "Setting"
    SYNC = "Sync"
    def icon(self, theme: Theme = ...) -> QIcon: ...

def setTheme(theme: Theme, save: bool = False, lazy: bool = False) -> None: ...
def isDarkTheme() -> bool: ...

class PushButton(QPushButton):
    @overload
    def __init__(self, parent: QWidget | None = None) -> None: ...
    @overload
    def __init__(self, text: str, parent: QWidget | None = None) -> None: ...

class PrimaryPushButton(PushButton): ...
class TransparentPushButton(PushButton): ...
class CheckBox(QCheckBox): ...

class LineEdit(QLineEdit):
    def __init__(self, parent: QWidget | None = None) -> None: ...

class SearchLineEdit(LineEdit): ...
class PlainTextEdit(QPlainTextEdit): ...
class SpinBox(QSpinBox): ...
class DoubleSpinBox(QDoubleSpinBox): ...
class ScrollArea(QScrollArea): ...

class TableView(QTableView):
    def setBorderVisible(self, isVisible: bool) -> None: ...
    def setBorderRadius(self, radius: int) -> None: ...

class TableWidget(QTableWidget):
    def __init__(self, parent: QWidget | None = None) -> None: ...
    def setBorderVisible(self, isVisible: bool) -> None: ...
    def setBorderRadius(self, radius: int) -> None: ...

class TreeWidget(QTreeWidget): ...

class ComboBox(QPushButton):
    currentIndexChanged: Signal
    def __init__(self, parent: QWidget | None = None) -> None: ...
    def addItems(self, texts: list[str]) -> None: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def currentIndex(self) -> int: ...
    def currentText(self) -> str: ...

class CaptionLabel(QLabel): ...
class BodyLabel(QLabel): ...
class StrongBodyLabel(QLabel): ...
class SubtitleLabel(QLabel): ...
class TitleLabel(QLabel): ...

class RoundMenu(QMenu):
    view: QListWidget
    def __init__(self, title: str = "", parent: QWidget | None = None) -> None: ...
    def setItemHeight(self, height: int) -> None: ...
    def exec(self, pos: QPoint, ani: bool = True) -> None: ...

class CheckableMenu(RoundMenu): ...
class ProgressBar(QProgressBar): ...

class IndeterminateProgressBar(QProgressBar):
    def __init__(self, parent: QWidget | None = None, start: bool = True) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...

class SegmentedWidget(QWidget):
    currentItemChanged: Signal
    def addItem(
        self, routeKey: str, text: str, onClick: Callable[[], object] | None = None
    ) -> QPushButton: ...
    def setCurrentItem(self, routeKey: str) -> None: ...
    def currentRouteKey(self) -> str | None: ...
