"""Deterministic VOX v13 formatting, independent of source conversion."""

from collections.abc import Iterable

from ksm2sdvx.chart.vox.effects import (
    FX_INTEGER_COLUMNS,
    FxEffect,
    LaserBitCrusher,
    LaserEffect,
    effect_columns,
)
from ksm2sdvx.chart.vox.model import (
    AirScale,
    Controller,
    ControllerName,
    ControllerSpan,
    ManualSpeed,
    MillisecondDuration,
    OpaqueRow,
    Realize,
    TrackEvent,
    VoxBtNote,
    VoxChart,
    VoxFxChip,
    VoxFxHold,
    VoxPosition,
)
from ksm2sdvx.chart.vox.scripts import script_lines
from ksm2sdvx.chart.vox.validation import validate_vox
from ksm2sdvx.chart.vox.values import field


def position(value: VoxPosition) -> str:
    return f"{value.measure:03},{value.beat:02},{value.tick:02}"


def section(name: str, rows: Iterable[str]) -> str:
    lines = list(rows)
    return f"#{name}\n" + ("\n".join(lines) + "\n" if lines else "") + "#END\n"


def track_row(event: TrackEvent) -> str:
    pos = position(event.position)
    if isinstance(event, (VoxBtNote, VoxFxChip, VoxFxHold)):
        if isinstance(event, VoxBtNote):
            duration, c2 = event.duration, event.unknown_c2
        elif isinstance(event, VoxFxChip):
            duration, c2 = 0, event.sample
        else:
            duration, c2 = event.duration, event.effect_pair
        row = f"{pos}\t{duration}\t{c2}"
        return row + (f"\t{event.cells_per_chain}" if event.cells_per_chain is not None else "")
    return "\t".join(
        map(
            str,
            (
                pos,
                f"{event.value:.6f}",
                int(event.marker),
                int(event.roll_type),
                event.effect,
                event.width,
                event.unused_c6,
                int(event.curve_type),
                event.unknown_c8,
                event.roll_length,
            ),
        )
    )


def clean(value: float) -> float:
    return 0.0 if abs(value) < 5e-13 else value


def decimal(value: float) -> str:
    """Two decimals where exact; preserve additional precision otherwise."""
    return f"{value:.2f}" if round(value, 2) == value else str(value)


def controller_row(event: Controller) -> str:
    pos = position(event.position)
    if isinstance(event, Realize):
        return f"{pos}\tRealize\t{event.controller}\t{event.c3:g}\t{decimal(event.c4)}\t{decimal(event.c5)}\t{decimal(event.c6)}\t{decimal(event.c7)}"
    if isinstance(event, AirScale):
        return f"{pos}\tAIR{'R' if event.right else 'L'}_ScaX\t{event.c2}\t{event.c3:g}\t{decimal(event.c4)}\t{decimal(event.c5)}\t{decimal(event.c6)}\t{decimal(event.c7)}"
    if isinstance(event, ControllerSpan):
        values = (
            tuple(f"d{decimal(clean(v))}" for v in (event.start_value, event.end_value))
            if event.name == ControllerName.ROTATION_Z
            else tuple(f"{clean(v):.9f}" for v in (event.start_value, event.end_value))
        )
        return f"{pos}\t{event.name.value}\t{event.start_mode}\t{event.duration}\t{values[0]}\t{values[1]}\t{int(event.node_type)}\t{event.unused_c7:.6f}"
    if isinstance(event, ManualSpeed):
        return f"{pos}\tManualSpeed\t{event.unknown_c2}\t0\tf{decimal(event.multiplier)}\t0.00\t0.00\t0.00"
    return "\t".join((pos, event.name.value, *(field(v) for v in event.fields)))


def effect_row(effect: FxEffect | LaserEffect, *, laser: bool = False) -> str:
    integers = (
        (2,)
        if isinstance(effect, LaserBitCrusher)
        else ()
        if laser
        else FX_INTEGER_COLUMNS[effect.kind]
    )
    return ",\t".join(
        str(v) if i == 0 or i in integers else decimal(v)
        for i, v in enumerate(effect_columns(effect))
    )


def opaque_rows(rows: tuple[OpaqueRow, ...]) -> Iterable[str]:
    return ("\t".join(field(v) for v in row.fields) for row in rows)


def serialize_vox(chart: VoxChart) -> str:
    validate_vox(chart)
    chunks = [
        "//====================================\n// SOUND VOLTEX OUTPUT TEXT FILE\n//====================================\n// Generated by ksm2sdvx\n",
        section("FORMAT VERSION", [str(chart.format_version)]),
    ]
    if chart.beat_resolution is not None:
        chunks.append(section("BEAT RESOLUTION", [str(chart.beat_resolution)]))
    chunks.extend(
        (
            section(
                "BEAT INFO",
                (f"{position(e.position)}\t{e.numerator}\t{e.denominator}" for e in chart.meters),
            ),
            section(
                "BPM INFO",
                (
                    f"{position(e.position)}\t{e.bpm:.4f}\t4{'-' if e.pause else ''}"
                    for e in chart.bpms
                ),
            ),
        )
    )
    if chart.bpm_options is not None:
        chunks.append(
            section(
                "BPM OPTION",
                (
                    f"ConstantScroll\t{int(chart.bpm_options.constant_scroll)}",
                    f"RepresentativeBpm\t{chart.bpm_options.representative_bpm:.4f}",
                ),
            )
        )
    chunks.extend(
        (
            section(
                "TILT MODE INFO",
                (f"{position(e.position)}\t{int(e.mode)}" for e in chart.tilt_modes),
            ),
            section("LYRIC INFO", opaque_rows(chart.lyrics)),
            section("END POSITION", [position(chart.end_position)]),
            section("TAB EFFECT INFO", (effect_row(e, laser=True) for e in chart.laser_effects)),
            section(
                "FXBUTTON EFFECT INFO",
                (effect_row(e) for pair in chart.fx_effects for e in (pair.first, pair.second)),
            ),
            section(
                "TAB PARAM ASSIGN INFO",
                (
                    f"{e.pair_index},\t{e.parameter},\t{decimal(e.from_value)},\t{decimal(e.to_value)}"
                    for e in chart.parameter_assignments
                ),
            ),
            section("REVERB EFFECT PARAM", opaque_rows(chart.reverb)),
        )
    )
    chunks.extend(
        section(f"TRACK{t.number}", (track_row(e) for e in t.events)) for t in chart.tracks
    )
    chunks.extend(
        (
            section(
                "TRACK AUTO TAB",
                (f"{position(e.position)}\t{e.duration}\t{e.effect_pair}" for e in chart.auto_tab),
            ),
            section("TRACK ORIGINAL L", (track_row(e) for e in chart.original_left)),
            section("TRACK ORIGINAL R", (track_row(e) for e in chart.original_right)),
            section("SPCONTROLER", (controller_row(e) for e in chart.controllers)),
        )
    )
    if chart.locked_controllers is not None:
        chunks.append(
            section("LOCKED_SPCONTROLER", (controller_row(e) for e in chart.locked_controllers))
        )
    if chart.post_effects is not None:
        chunks.append(
            section(
                "POSTEFFECT",
                (
                    "\t".join(
                        (
                            position(e.position),
                            str(e.unknown_c1),
                            str(e.duration.value)
                            + ("ms" if isinstance(e.duration, MillisecondDuration) else ""),
                            e.name.value,
                            str(e.unknown_c4),
                            str(e.unknown_c5),
                            e.parameter,
                            f"{e.start_value}f",
                            f"{e.end_value}f",
                        )
                    )
                    for e in chart.post_effects
                ),
            )
        )
    if chart.scripts is not None:
        chunks.append(
            section("SCRIPT_DEFINE", (line for s in chart.scripts for line in script_lines(s)))
        )
    chunks.extend(
        section(
            f"SCRIPTED_TRACK{t.number}",
            (f"{position(a.position)} {' '.join(map(str, a.script_ids))}" for a in t.applications),
        )
        for t in chart.scripted_tracks
    )
    return "\n".join(chunks)
